[package]
name = "checkers"
version = "0.4.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/checkers"
homepage = "https://github.com/udoprog/checkers"
documentation = "https://docs.rs/checkers"
description = """
A sanity checker for global allocations.
"""
keywords = ["memory", "heap", "allocator"]
categories = ["memory-management", "development-tools"]

[dependencies]
checkers-macros = {path = "./macros", version = "0.3.0"}